jobs:
  include:
    - name: api
      language: elixir
      sudo: false
      elixir: 1.9
      otp_release: 22.1
      cache:
        directories:
          - api/_build
          - api/deps
      env: MIX_ENV=test
      before_install:
        - cd api
      before_script:
        - mix do ecto.create, ecto.migrate
      script:
        - mix test
        - mix format --check-formatted
        - mix credo
    - name: Web
      language: node_js
      node_js: "lts/*"
      cache: yarn
      before_install:
        - cd Web
      script:
        - yarn lint
        - yarn test

branches:
  only:
    - master
