jobs:
  include:
    - name: api
      language: elixir
      sudo: false
      elixir: 1.9
      otp_release: 22.1
      cache:
        directories:
          - api/_build
          - api/deps
      services:
        - postgresql
      env: MIX_ENV=test
      before_install:
        - cd api
      before_script:
        - mix do ecto.create, ecto.migrate
      script:
        - mix test
        - mix format --check-formatted
        - mix credo
    - name: Web
      language: node_js
      node_js: "lts/*"
      cache: yarn
      before_install:
        - cd Web
      script:
        - yarn typecheck
        - yarn lint
        - yarn lint:css
        - yarn test
        - yarn build
        - for i in build/static/*/*; do mv "$i" "$(echo "$i" | sed -E 's/(.*)\.[a-f0-9]{8}(.*)/\1\2/')"; done
        - mv build/precache-manifest.*.js build/precache-manifest.js
        - yarn run bundlewatch --max-size 100kb ./build/**/*.js

branches:
  only:
    - master
