version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinda
    expose:
      - "5432"
  api:
    build:
      context: ./api
    volumes:
      - ./api:/api
    ports:
      - "4000:4000"
      - "5000:5000"
    secrets:
      - "server.key"
      - "server.crt"
    environment:
      SSL_KEY_PATH: /run/secrets/server.key
      SSL_CERT_PATH: /run/secrets/server.crt
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pinda
    depends_on:
      - postgres
  web:
    build:
      context: ./Web
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=2000
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./Web:/home/node/app
    expose:
      - "3000"
    depends_on:
      - api
  proxy:
    image: nginx:1.14.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - "server.key"
      - "server.crt"
    depends_on:
      - web

volumes:
  yarn:
  postgres:

secrets:
  "server.key":
    file: ./proxy/server.key
  "server.crt":
    file: ./proxy/server.crt
