@startuml
scale 2

interface BaseMeta {
  isHost: boolean
  name: string
  result: number[] | null
}

interface HostMeta {
  isHost: true
  seed: string
}

interface NonHostMeta {
  isHost: false
}

enum GameState {
  FINISHED
  PREPARE
  ONGOING
}

enum Game {
  SHAKE
  SUMS
  SEQUENCE
}

BaseMeta <|-- HostMeta
BaseMeta <|-- NonHostMeta

HostMeta "1" *--  "1" GameState: "state"
HostMeta "1" *--  "1" Game: "game"

@enduml
